better help from parser

diff --git a/bash/teleport b/bash/teleport
--- a/bash/teleport
+++ b/bash/teleport
@@ -1,10 +1,8 @@
 #!/usr/bin/env bash
-function tp() {
-    OUTPUT=`teleport-hask $@`
-    # return code 2 is used to indicate that the shell script
-    # should use the output to warp to
-    if [ $? -eq 2 ]
-        then cd "$OUTPUT"
-        else echo "$OUTPUT"
-    fi
-}
+OUTPUT=`teleport-hask $@`
+# return code 2 is used to indicate that the shell script
+# should use the output to warp to
+if [ $? -eq 2 ]
+    then cd "$OUTPUT"
+    else echo "$OUTPUT"
+fi
